services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - DISABLE_CORS_CHECKS=1
      - SKIP_CORS_CHECK=1
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:4566
      - CORS_ALLOWED_HEADERS=authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging
      - CORS_ALLOWED_METHODS=HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
      - EXTRA_CORS_ALLOWED_HEADERS=x-amz-request-id,x-amz-id-2
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-net

  cors-proxy:
    image: nginx:alpine
    ports:
      - "4566:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - localstack
    networks:
      - localstack-net

networks:
  localstack-net:
